### PR TITLE
Remove deprecated ls and cat commands

### PR DESCRIPTION
**Pull request by sungwoncho**
* Remove `ls` and `cat` commands which were deprecated in [v0.4.0](https://github.com/dnote/cli/releases/tag/v0.4.0).
* They are replaced by `view`
* Will be released in v0.5.0

### CODE REVIEW

**Comment by michielboekhoff** [comment]
Just a question: are you following SemVer?

**Comment by sungwoncho** [comment]
@michielboekhoff yes, did you spot any problem with releases?

**Comment by michielboekhoff** [comment]
Not with the releases, but removing deprecated code tends to happen with
major releases (e.g. 1.0.0 to 2.0.0).

**Comment by sungwoncho** [comment]
You're right.

> Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

https://semver.org/#how-should-i-handle-deprecating-functionality

I will revert this and wait until 1.0.0.

**Pull request merged**
